import { NextResponse } from 'next/server';

const frontendWisdoms = [
  "Center an element with `display: flex; justify-content: center; align-items: center;`",
  "Don't repeat yourself. If you're writing the same HTML twice, there's probably a component for that.",
  "Accessibility is not a feature; it's a requirement.",
  "Never trust data from the frontend. Always validate on the server.",
  "Use `rem` for font sizes to make scaling with the root element easy.",
  "A good developer leaves the code better than they found it.",
  "Frontend isn’t just code - it’s crafting experiences that people remember.",
  "If it works in Chrome, test it in Firefox. If it works in Firefox, test it in Safari. If it works in Safari, good luck.",
  "CSS: Where 1px can ruin your day.",
  "The only thing harder than naming things is centering them.",
  "If you think you understand CSS, you haven’t met `position: absolute` yet.",
  "Frontend: Where ‘just one more pixel’ is a lifestyle.",
  "If you ever feel useless, remember there’s a `float: left` somewhere in production.",
  "React: Because writing HTML in JavaScript is totally normal.",
  "The quickest way to learn regex is to copy it from Stack Overflow.",
  "The only thing more mysterious than the Bermuda Triangle is CSS specificity.",
  "Frontend: Where ‘works on my machine’ is a valid excuse.",
  "If you ever feel lost, just remember: `console.log` is your best friend.",
  "The only thing more flexible than flexbox is your patience.",
  "Frontend: Where ‘just a quick fix’ takes all afternoon.",
  "CSS Grid: Because sometimes you want to feel like a wizard.",
  "If you don’t have at least 10 tabs open, are you even debugging?",
  "Frontend: Where ‘responsive’ means ‘surprise!’",
  "If you can write a regex that works first try, you’re lying.",
  "Frontend: Where ‘just update the package’ breaks everything.",
  "Frontend: Where ‘just one more feature’ means a rewrite.",
  "If you can make a modal work everywhere, you’re a wizard.",
  "The only thing more mysterious than `this` is `bind(this)`.",
  "If you ever feel brave, try updating dependencies.",
  "If you can explain why your code works, you’re overqualified.",
  "Frontend: Where ‘just add a loader’ is a lifestyle.",
  "Frontend: Where ‘just one more breakpoint’ is never enough.",

  
  "If you can explain why your layout broke, you’re a genius.",
  "The only thing more magical than `box-shadow` is `filter: blur()`.",
  "If you don’t use `useEffect`, do you even React?",
  "Frontend: Where ‘just add a spinner’ solves everything.",
  "If you can make a sticky header work, you’re a legend.",
  "The only thing more confusing than `vh` and `vw` is `em` and `rem`.",
  "If you ever feel stuck, try turning it off and on again.",
  "Frontend: Where ‘just update the style’ means rewrite the component.",
  "If you can explain why your animation is janky, you’re a wizard.",
  "The only thing more persistent than a bug is a deadline.",
  "If you don’t use `map`, do you even JavaScript?",
  "Frontend: Where ‘just add a transition’ is a solution.",
  "If you can make a tooltip work everywhere, you’re a hero.",
  "The only thing more mysterious than `overflow: hidden` is `overflow: scroll`.",
  "If you ever feel overwhelmed, remember: There’s always a framework for that.",
  "Frontend: Where ‘just add a class’ means refactor everything.",
  "If you can explain why your font isn’t loading, you’re a genius.",
  "The only thing more magical than `border-radius` is `clip-path`.",
  "If you don’t use `useState`, do you even React?",
  "Frontend: Where ‘just add a media query’ is a lifestyle.",
  "If you can make a hamburger menu work, you’re a legend.",
  "The only thing more confusing than `display: inline-block` is `display: contents`.",
  "If you ever feel lost, remember: There’s always a div for that.",
  "Frontend: Where ‘just add a prop’ means rewrite the component.",
  "If you can explain why your SVG isn’t rendering, you’re a wizard.",
  "The only thing more persistent than a bug is a merge conflict.",
  "If you don’t use `filter`, do you even JavaScript?",
  "Frontend: Where ‘just add a key’ solves everything.",
  "If you can make a modal accessible, you’re a hero.",
  "The only thing more mysterious than `pointer-events: none` is `pointer-events: auto`.",
  "If you ever feel tired, remember: There’s always a build tool for that.",
  "Frontend: Where ‘just add a ref’ is a solution.",
  "If you can explain why your grid isn’t aligning, you’re a genius.",
  "The only thing more magical than `transform: scale()` is `transform: rotate()`.",
  "If you don’t use `reduce`, do you even JavaScript?",
  "Frontend: Where ‘just add a hook’ is a lifestyle.",
  "If you can make a dropdown accessible, you’re a legend.",
  "The only thing more confusing than `flex-wrap` is `flex-shrink`.",
  "If you ever feel stuck, remember: There’s always a workaround.",
  "Frontend: Where ‘just add a fallback’ solves everything.",
  "If you can explain why your image isn’t loading, you’re a wizard.",
  "The only thing more persistent than a bug is a hotfix.",
  "If you don’t use `find`, do you even JavaScript?",
  "Frontend: Where ‘just add a theme’ means rewrite everything.",
  "If you can make a carousel work, you’re a hero.",
  "The only thing more mysterious than `object-fit` is `object-position`.",
  "If you ever feel overwhelmed, remember: There’s always a library for that.",
  "Frontend: Where ‘just add a transition’ is a solution.",
  "If you can explain why your button isn’t clickable, you’re a genius.",
  "The only thing more magical than `opacity` is `visibility`.",
  "If you don’t use `forEach`, do you even JavaScript?",
  "Frontend: Where ‘just add a context’ is a lifestyle.",
  "If you can make a sidebar responsive, you’re a legend.",
  "The only thing more confusing than `min-width` is `max-width`.",
  "If you ever feel lost, remember: There’s always a span for that.",
  "Frontend: Where ‘just add a loader’ solves everything.",
  "If you can explain why your link isn’t working, you’re a wizard.",
  "The only thing more persistent than a bug is a feature creep.",
  "If you don’t use `splice`, do you even JavaScript?",
  "Frontend: Where ‘just add a polyfill’ solves everything.",
  "Frontend: Where ‘just add a wrapper’ is a solution.",
  "Frontend: Where ‘just add a fallback’ is a lifestyle.",
  "If you can make a tooltip accessible, you’re a hero.",
  "If you ever feel overwhelmed, remember: There’s always a new framework tomorrow.",
];

export async function GET() {
    return NextResponse.json(frontendWisdoms);
}
